config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  authenticated do  	
  	resources :projects do 
	   	resources :tasks do
	   		get 'assign_task/:id', to: 'tasks#assign_task', as: :assign_task
	   		get 'remove_task/:id', to: 'tasks#assign_task', as: :remove_task
	   	end
   	end
  end

  devise_for :users
  unauthenticated do
		devise_scope :user do
		  root to: "devise/sessions#new"
		end
  end
  root to: "projects#index"

end

app/models/task.rb
class Task < ApplicationRecord
	resourcify
	enum status: { on_hold: 1, in_progress: 2, completed: 3 }
  belongs_to :project
  belongs_to :created_by, :class_name => 'User', :foreign_key => 'created_by_id'
  attr_accessor :developer_id

  validates :created_by, presence: true
  validates :project, presence: true
  validates :title, presence: true

  def assign_task(user)
  	remove_task
  	user.add_role :developer, self
  end

  def remove_task
  	# user.remove_role :developer, self 
    self.roles.where(:name => 'developer').delete_all if self.roles.pluck(:name).include? ('developer')
  end

  def developer
    self.roles.first.users.first if !self.roles.blank?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_developer, only: [:assign_task,:update,:create]
  before_action :set_task, only: [:show, :edit, :update, :destroy, :assign_task]
  
  load_and_authorize_resource

  # GET /tasks
  # GET /tasks.json
  def index
    if current_user.has_role(:admin)
      @tasks = Task.all
    elsif current_user.has_role(:developer)
      @tasks = Task.with_role(:developer, current_user)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build(:project_id => params[:project_id])
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)
    @task.project_id = params[:project_id]
    respond_to do |format|
      if @task.save
        assign_task
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
      # puts "============checking params from update"
      # puts task_params.inspect
    respond_to do |format|
      if @task.update(task_params)
        assign_task
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    # byebug
    @task.destroy
    respond_to do |format|
      format.js {}
      format.html { redirect_to project_tasks_url(@task.project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_developer
      # byebug
      @developer=User.find_by(:id => task_params[:developer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:id,:title, :description, :project_id,:developer_id, :created_by_id, :status)
    end

    def assign_task
      @task.assign_task(@developer)
    end

    # def remove_task
    #   @task.remove_task(@developer)
    # end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for([@task.project,@task],:remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%#= f.hidden_field :project,:value => @task.project %>
    <%#= f.association :created_by %>
    <%= f.input :status, collection: Task.statuses.keys, include_blank: false %>
    <%= f.input :developer_id, collection: User.all.map{|user| [user.email,user.id]} , include_blank: false, selected: (@task.developer ? @task.developer.id : current_user.id) %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% developers = task.roles.first.users.pluck(:email).join(', ') %>
<tr id="<%= dom_id(task) %>">
	<!-- <td><%#= task.project.name %></td> -->
	<td><%= task.title %></td>
	<td><%= task.description %></td>
	<td><%= task.created_by.email %></td>
	<td><%= developers %></td>
	<td><%= task.status %></td>
	<td><%= link_to 'Edit', edit_project_task_path(task.project,task) ,:remote => true if can? :update,task  %></td>
	<td><%= link_to 'Destroy', project_task_path(task.project.id,task),:remote => true, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete,Task %></td>
</tr>

app/views/tasks/create.js.erb
<% if @task %>
$('#<%= @task.status %> .table tbody').prepend('<%= escape_javascript(render partial: @task) %>');

$('span#total-tasks-count').html("<%= @task.project.tasks.size %>")
$('span#on-hold-count').html("<%= @task.project.tasks.on_hold.size %>")
$('span#in-progress-count').html("<%= @task.project.tasks.in_progress.size %>")
$('span#completed-count').html("<%= @task.project.tasks.completed.size %>")

$('#tasks-stat-graph').html("<img src='<%= Gchart.pie_3d(:title => @task.project.name, :labels => Task.statuses.keys, :data => [@task.project.tasks.on_hold.size,@task.project.tasks.in_progress.size,@task.project.tasks.completed.size], :size => '400x200') %>'/>")
	



$('#new-modal').modal('hide');
<% end %>

app/views/tasks/destroy.js.erb
$("#" + "<%= dom_id @task %>").fadeOut(600, function() { $(this).remove(); });

$('span#total-tasks-count').html("<%= @task.project.tasks.size %>")
$('span#on-hold-count').html("<%= @task.project.tasks.on_hold.size %>")
$('span#in-progress-count').html("<%= @task.project.tasks.in_progress.size %>")
$('span#completed-count').html("<%= @task.project.tasks.completed.size %>")
$('#tasks-stat-graph').html("<img src='<%= Gchart.pie_3d(:title => @task.project.name, :labels => Task.statuses.keys, :data => [@task.project.tasks.on_hold.size,@task.project.tasks.in_progress.size,@task.project.tasks.completed.size], :size => '400x200') %>'/>")

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>


<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/edit.js.erb
<%
output='<div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Edit Task</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">'
output=output + (render "form",:task => @task)
output=output + '</div>

    </div>
  </div>'
%>
$("body #new-modal").html('<%= escape_javascript(raw(output)) %>');

$('#new-modal').modal('show');

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
<%
output='<div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">New Task</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">'
output=output + (render "form",:task => @task)
output=output + '</div>

    </div>
  </div>'
%>
$("body #new-modal").html('<%= escape_javascript(raw(output)) %>');

$('#new-modal').modal('show');

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.name %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @task.created_by.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task.project,@task) %> |
<%= link_to 'Back', projects_path() %>

app/views/tasks/update.js.erb
$('.table tbody tr#<%= dom_id @task %>' ).hide();
$('#<%= @task.status %> .table tbody').prepend('<%= escape_javascript(render partial: @task) %>');

$('span#total-tasks-count').html("<%= @task.project.tasks.size %>")
$('span#on-hold-count').html("<%= @task.project.tasks.on_hold.size %>")
$('span#in-progress-count').html("<%= @task.project.tasks.in_progress.size %>")
$('span#completed-count').html("<%= @task.project.tasks.completed.size %>")
$('#tasks-stat-graph').html("<img src='<%= Gchart.pie_3d(:title => @task.project.name, :labels => Task.statuses.keys, :data => [@task.project.tasks.on_hold.size,@task.project.tasks.in_progress.size,@task.project.tasks.completed.size], :size => '400x200') %>'/>")


$('#new-modal').modal('hide');