config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  authenticated do  	
  	resources :projects do 
	   	resources :tasks do
	   		get 'assign_task/:id', to: 'tasks#assign_task', as: :assign_task
	   		get 'remove_task/:id', to: 'tasks#assign_task', as: :remove_task
	   	end
   	end
  end

  devise_for :users
  unauthenticated do
		devise_scope :user do
		  root to: "devise/sessions#new"
		end
  end
  root to: "projects#index"

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :created_by, :class_name => 'User', :foreign_key => 'created_by_id'
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
  validates :created_by, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    if current_user.has_role?(:admin)
      @projects = Project.order(id: :desc).paginate(:page => params[:page], :per_page => 10)
    elsif current_user.has_role?(:developer)
      @tasks = Task.with_role(:developer, current_user)
      @projects = Project.where('id in (?)',@tasks.pluck(:project_id).to_a).order(id: :desc).paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project_tasks = @project.tasks.order(id: :desc)
    @on_hold_tasks = @project_tasks.on_hold
    @in_progress_tasks = @project_tasks.in_progress
    @completed_tasks = @project_tasks.completed
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.js {}
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :created_by_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project,:remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%#= f.association :created_by, :label_method => :email, :value_method => :id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn-primary' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<% if can? :read,project %>
<tr id="<%= dom_id project %>">
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.created_by.email %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project),:remote => true if can? :update,Project %></td>
        <td><%= link_to 'Destroy', project, :remote => true, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete,Project %></td>
</tr>
<% end %>

app/views/projects/create.js.erb
<% if @project %>
$('.table tbody').prepend('<%= escape_javascript(render partial: @project) %>');
$('#new-modal').modal('hide');
<% end %>

app/views/projects/destroy.js.erb
$("#" + "<%= dom_id @project %>").fadeOut(600, function() { $(this).remove(); });

app/views/projects/edit.js.erb
<%
output='<div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Edit Project</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">'
output=output + (render "form",:project => @project)
output=output + '</div>

    </div>
  </div>'
%>
$("body #new-modal").html('<%= escape_javascript(raw(output)) %>');

$('#new-modal').modal('show');

app/views/projects/index.html.erb
<h1>Projects</h1>
<br/>
<%= link_to raw('New Project>'), new_project_path, :class => 'btn btn-primary',:remote => true if can? :create,Project %>
<br/><br/>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render partial: @projects %>
  </tbody>
</table>

<br/>
<%= will_paginate @projects %>

app/views/projects/new.js.erb
<%
output='<div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">New Project</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">'
output=output + (render "form",:project => @project)
output=output + '</div>

    </div>
  </div>'
%>
$("body #new-modal").html('<%= escape_javascript(raw(output)) %>');

$('#new-modal').modal('show');

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path %> | <%= link_to 'Edit', edit_project_path(@project),:remote => true if can? :update,Project %>
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>




<div class="row">
  <div id="tasks-stat-graph" class="col">
	<img src="<%= Gchart.pie_3d(:title => @project.name, :labels => Task.statuses.keys, :data => [@on_hold_tasks.size,@in_progress_tasks.size,@completed_tasks.size], :size => '400x200') %>"/>
	</div>
	<div class="col pie_chart_details">
		<p>
        <strong>Total Tasks</strong> : <span id="total-tasks-count"><%= @project_tasks.size %></span><br/>
		<strong>On Hold</strong> : <span id="on-hold-count"><%= @on_hold_tasks.size %></span><br/>
		<strong>In Progress</strong> : <span id="in-progress-count"><%= @in_progress_tasks.size %></span><br/>
		<strong>Completed</strong> : <span id="completed-count"><%= @completed_tasks.size %></span>
		</p>
	</div>
</div>
<p>
  <strong>Created by:</strong>
  <%= @project.created_by.email %>
</p>

<section class="container task-list">


        <div class="row">
        	<div class="col-md-10 text-center">
                <h2>Tasks</h2>
            </div>
            <div class="col-md-2 text-center">
                <div class="text-center">
                    <%= link_to 'New Task', new_project_task_path(@project),:remote => true, :class => 'btn btn-primary' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <ul id="tabsJustified" class="nav nav-tabs">
                    <li class="nav-item"><a href="" data-target="#on_hold" data-toggle="tab" class="nav-link small text-uppercase active">On Hold</a></li>
                    <li class="nav-item"><a href="" data-target="#in_progress" data-toggle="tab" class="nav-link small text-uppercase">In Progress</a></li>
                    <li class="nav-item"><a href="" data-target="#completed" data-toggle="tab" class="nav-link small text-uppercase">Completed</a></li>
                </ul>
                <br>
                <div id="tabsJustifiedContent" class="tab-content">
                    <div id="on_hold" class="tab-pane fade active show">
						<table class="table">
						  <thead>
						    <tr>
                  <!-- <th>Project</th> -->
						      <th>Title</th>
						      <th>Description</th>
						      <th>Created by</th>
						      <th>Assigned to</th>
						      <th>Status</th>
						      <th colspan="3"></th>
						    </tr>
						  </thead>

						  <tbody>
						  <%= render partial: "tasks/task", collection: @on_hold_tasks, as: :task %>
						  </tbody>
						</table>


                    </div>
                    <div id="in_progress" class="tab-pane fade">
                        <table class="table">
                          <thead>
                            <tr>
                              <!-- <th>Project</th> -->
                              <th>Title</th>
                              <th>Description</th>
                              <th>Created by</th>
                              <th>Assigned to</th>
                              <th>Status</th>
                              <th colspan="3"></th>
                            </tr>
                          </thead>

                          <tbody>
                          <%= render partial: "tasks/task", collection: @in_progress_tasks, as: :task %>
                          </tbody>
                        </table>
                    </div>
                    <div id="completed" class="tab-pane fade">
                        <table class="table">
                          <thead>
                            <tr>
                              <!-- <th>Project</th> -->
                              <th>Title</th>
                              <th>Description</th>
                              <th>Created by</th>
                              <th>Assigned to</th>
                              <th>Status</th>
                              <th colspan="3"></th>
                            </tr>
                          </thead>

                          <tbody>
                          <%= render partial: "tasks/task", collection: @completed_tasks, as: :task if @completed_tasks %>
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/projects/update.js.erb
$('.table tbody tr#' + '<%= dom_id @project %>' ).replaceWith('<%= escape_javascript(render partial: @project) %>');
$('#new-modal').modal('hide');